const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
// Itens removidos do catálogo a pedido do proprietário.
window.PRODUTOS = (window.PRODUTOS || []).filter(p => ![22,23,24,25,26,1123,1125,1126,1127,1129,1131,1135,1140,1141].includes(Number(p.id)));
const state={favorites:JSON.parse(localStorage.getItem('glt-favorites')||'[]')};
const contacts={whatsapp:'5537998268978',instagram:'https://www.instagram.com/glt_imports/'};
const logo=()=>`<span class="logo"><span>GLT</span></span>`;
function save(){localStorage.setItem('glt-favorites',JSON.stringify(state.favorites));updateCount()}
function card(p){const fav=state.favorites.includes(p.id);return `<article class="product-card reveal" data-product="${p.id}"><a class="product-media" href="produto.html?id=${p.id}"><img src="${p.img}" alt="${p.nome}" loading="lazy"></a><button class="heart ${fav?'active':''}" data-fav="${p.id}" aria-label="${fav?'Remover':'Adicionar'} favorito">${fav?'♥':'♡'}</button><div class="product-info"><span class="product-brand">${p.marca}</span><h3><a href="produto.html?id=${p.id}">${p.nome}</a></h3><span class="product-meta">ID ${p.id} · ${p.categoria} / ${p.tipo}</span><div class="product-foot"><span class="price">${money(p.preco)}</span><a class="detail-link" href="produto.html?id=${p.id}">VER DETALHES →</a></div></div></article>`}
function header(){const h=$('#siteHeader');if(!h)return;h.innerHTML=`<style>.search-action{overflow:visible}.search-hint{display:block;position:absolute;left:50%;top:34px;transform:translateX(-50%);color:var(--orange);font-size:6px;font-weight:700;letter-spacing:1px;white-space:nowrap;opacity:.8}</style><header class="header"><a class="brand" href="index.html">${logo()}<span class="brand-name">GLT IMPORTS</span></a><nav class="nav" id="nav"><a href="index.html">Início</a><a href="produtos.html?cat=Chuteiras">Chuteiras</a><a href="produtos.html?cat=Camisas">Camisas</a><a href="produtos.html?cat=Tênis">Tênis</a><a href="produtos.html?cat=Luxo">Luxo</a><a href="produtos.html?cat=Joias">Joias</a><a href="produtos.html?cat=Acessórios">Acessórios</a></nav><div class="actions"><button class="icon-btn search-action" data-search aria-label="Pesquisar" title="Pesquisar produtos">⌕<span class="search-hint">PESQUISAR</span></button><a class="icon-btn" href="favoritos.html" aria-label="Favoritos">♡<span class="fav-count is-empty" style="display:none">0</span></a><a class="icon-btn" href="produtos.html" aria-label="Catálogo">▦</a><button class="icon-btn hamb" data-menu aria-label="Abrir menu">☰</button></div></header>`}
function footer(){const f=$('#siteFooter');if(!f)return;f.innerHTML=`<footer class="footer"><div class="footer-top"><div><a class="brand" href="index.html">${logo()}<span class="brand-name">GLT IMPORTS</span></a><p>Futebol, moda e cultura para quem vive o jogo além das quatro linhas.</p></div><div><h4>NAVEGAÇÃO</h4><a href="index.html">Início</a><a href="produtos.html">Catálogo</a><a href="favoritos.html">Favoritos</a></div><div><h4>CATEGORIAS</h4><a href="produtos.html?cat=Chuteiras">Chuteiras</a><a href="produtos.html?cat=Camisas">Camisas</a><a href="produtos.html?cat=Tênis">Tênis</a><a href="produtos.html?cat=Luxo">Luxo e joias</a></div><div><h4>CONTATO</h4><a href="https://wa.me/${contacts.whatsapp}" target="_blank" rel="noopener">WhatsApp: (37) 9 9826-8978</a><a href="${contacts.instagram}" target="_blank" rel="noopener">Instagram: @glt_imports</a><a href="mailto:contato@gltimports.com">contato@gltimports.com</a><a href="#">Privacidade</a><a href="#">Termos de uso</a></div></div><div class="footer-statement">O JOGO É <span>MAIS</span> QUE 90 MINUTOS.</div><div class="copyright">© 2026 GLT IMPORTS. CATÁLOGO DEMONSTRATIVO.</div></footer>`}
function overlays(){document.body.insertAdjacentHTML('beforeend',`<div class="search-panel"><button class="close-search">×</button><label>PESQUISE O UNIVERSO GLT</label><input id="searchInput" type="search" placeholder="Nome, categoria, marca ou tipo"><div class="product-grid search-results" id="searchResults"></div></div><div class="modal-backdrop"></div><div class="contact-modal"><button class="modal-close">×</button><span class="kicker">GLT CONCIERGE</span><h2>CONSULTAR PRODUTO</h2><p>Escolha o canal e fale com a nossa curadoria sobre disponibilidade, tamanhos e cores.</p><div class="contact-options"><a id="whatsappLink" href="#" target="_blank" rel="noopener">WHATSAPP: (37) 9 9826-8978</a><a href="${contacts.instagram}" target="_blank" rel="noopener">INSTAGRAM: @glt_imports</a><a id="emailLink">E-MAIL ↗</a></div></div>`)}
function updateCount(){$$('.fav-count').forEach(x=>{const count=state.favorites.length;x.textContent=count;x.style.display=count===0?'none':'';x.classList.toggle('is-empty',count===0)})}
function toggleFav(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();$$(`[data-fav="${id}"]`).forEach(b=>{const yes=state.favorites.includes(id);b.classList.toggle('active',yes);b.textContent=yes?'♥':'♡'});document.dispatchEvent(new Event('gltFavorites'))}
function contact(p){const name=p?.nome||'um produto GLT';const message=`Olá! Gostaria de consultar o produto: ${name}.`;$('#whatsappLink').href=`https://wa.me/${contacts.whatsapp}?text=${encodeURIComponent(message)}`;$('#emailLink').href=`mailto:contato@gltimports.com?subject=${encodeURIComponent('Consulta: '+name)}`;$('.modal-backdrop').classList.add('open');$('.contact-modal').classList.add('open');document.body.classList.add('lock')}
function closeContact(){$('.modal-backdrop').classList.remove('open');$('.contact-modal').classList.remove('open');document.body.classList.remove('lock')}
function init(){header();footer();overlays();updateCount();document.addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){e.preventDefault();toggleFav(+fav.dataset.fav)}if(e.target.closest('[data-menu]'))$('#nav').classList.toggle('open');if(e.target.closest('[data-search]')){$('.search-panel').classList.add('open');$('#searchInput').focus()}if(e.target.matches('.close-search'))$('.search-panel').classList.remove('open');if(e.target.matches('.modal-close,.modal-backdrop'))closeContact();const consult=e.target.closest('[data-consult]');if(consult)contact(PRODUTOS.find(p=>p.id===+consult.dataset.consult))});$('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();$('#searchResults').innerHTML=q?PRODUTOS.filter(p=>[p.nome,p.categoria,p.marca,p.tipo].join(' ').toLowerCase().includes(q)).map(card).join(''):''});window.addEventListener('scroll',()=>$('.header').classList.toggle('scrolled',scrollY>20));const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});setInterval(()=>$$('.reveal:not(.visible)').forEach(x=>observer.observe(x)),300);setTimeout(()=>$('.loader')?.classList.add('hide'),950);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('.search-panel').classList.remove('open');closeContact()}})}
document.addEventListener('DOMContentLoaded',init);window.GLT={card,state,toggleFav,money,contact};
